import type { SeedMenuItem } from './seed-data';

/**
 * Mutfak türüne göre menüler.
 *
 * Katalogdaki 14 restoranın her birine ayrı menü yazmak yerine mutfak türüne
 * göre menü tanımlanıyor: gerçek hayatta da iki dönerci menüsü birbirine
 * benzer. Benzemeyen şey fiyat ve isim; onlar zaten işletmeye özel.
 *
 * Türü olmayan restoran menüsüz kalıyor ve menü bölümü hiç çizilmiyor —
 * boş bir "Menü" başlığı, menüsü olmadığını söylemenin en kötü yolu.
 */

export const MUTFAK_MENULERI: Record<string, SeedMenuItem[]> = {
  kebapci: [
    { category: 'Başlangıçlar', name: 'Mercimek çorbası', price: 90 },
    { category: 'Başlangıçlar', name: 'Acılı ezme', price: 95 },
    { category: 'Başlangıçlar', name: 'Yoğurtlu patlıcan', price: 110 },
    { category: 'Kebaplar', name: 'Adana kebap', description: 'Közlenmiş biber ve domates ile', price: 390 },
    { category: 'Kebaplar', name: 'Urfa kebap', description: 'Acısız', price: 390 },
    { category: 'Kebaplar', name: 'Beyti sarma', price: 460 },
    { category: 'Kebaplar', name: 'Patlıcan kebabı', price: 430 },
    { category: 'Kebaplar', name: 'Kuzu şiş', price: 490 },
    { category: 'Tatlılar', name: 'Künefe', price: 170 },
    { category: 'Tatlılar', name: 'Baklava', description: 'Porsiyon', price: 180 },
    { category: 'İçecekler', name: 'Ayran', price: 45 },
    { category: 'İçecekler', name: 'Şalgam', price: 45 },
  ],
  donerci: [
    { category: 'Dönerler', name: 'Et döner porsiyon', description: '150 gr, pilav üstü', price: 320 },
    { category: 'Dönerler', name: 'Tavuk döner porsiyon', price: 250 },
    { category: 'Dönerler', name: 'İskender', description: 'Tereyağı ve yoğurt ile', price: 420 },
    { category: 'Dürüm & Ekmek', name: 'Et dürüm', price: 220 },
    { category: 'Dürüm & Ekmek', name: 'Tavuk dürüm', price: 170 },
    { category: 'Dürüm & Ekmek', name: 'Ekmek arası et döner', price: 200 },
    { category: 'Öğle menüsü', name: 'Dürüm + ayran + salata', description: 'Hafta içi 11:00-15:00', price: 260 },
    { category: 'İçecekler', name: 'Ayran', price: 40 },
    { category: 'İçecekler', name: 'Şalgam', price: 40 },
    { category: 'İçecekler', name: 'Kola', price: 55 },
  ],
  evYemegi: [
    { category: 'Çorbalar', name: 'Ezogelin', price: 85 },
    { category: 'Çorbalar', name: 'Tarhana', price: 85 },
    { category: 'Sulu yemek', name: 'Kuru fasulye', description: 'Pilav ve turşu ile', price: 230 },
    { category: 'Sulu yemek', name: 'Etli nohut', price: 240 },
    { category: 'Sulu yemek', name: 'Karnıyarık', price: 270 },
    { category: 'Sulu yemek', name: 'Türlü', price: 240 },
    { category: 'Sulu yemek', name: 'Taze fasulye', price: 220 },
    { category: 'Ek', name: 'Pirinç pilavı', price: 90 },
    { category: 'Ek', name: 'Cacık', price: 70 },
    { category: 'Tatlılar', name: 'Sütlaç', price: 120 },
    { category: 'Tatlılar', name: 'Kemalpaşa', price: 130 },
    { category: 'İçecekler', name: 'Ayran', price: 40 },
  ],
  mangal: [
    { category: 'Başlangıçlar', name: 'Közlenmiş patlıcan', price: 120 },
    { category: 'Başlangıçlar', name: 'Ezme', price: 100 },
    { category: 'Başlangıçlar', name: 'Gavurdağı', price: 130 },
    { category: 'Mangal', name: 'Kuzu pirzola', description: '350 gr', price: 580 },
    { category: 'Mangal', name: 'Kanat', description: '8 adet', price: 320 },
    { category: 'Mangal', name: 'Köfte', price: 300 },
    { category: 'Mangal', name: 'Tavuk şiş', price: 290 },
    { category: 'Mangal', name: 'Karışık mangal', description: '2-3 kişilik', price: 1150 },
    { category: 'Tatlılar', name: 'Fırın sütlaç', price: 130 },
    { category: 'İçecekler', name: 'Ayran', price: 45 },
    { category: 'İçecekler', name: 'Limonata', price: 90 },
  ],
  pide: [
    { category: 'Pideler', name: 'Kıymalı pide', price: 210 },
    { category: 'Pideler', name: 'Kaşarlı pide', price: 220 },
    { category: 'Pideler', name: 'Kuşbaşılı kaşarlı', price: 280 },
    { category: 'Pideler', name: 'Karadeniz pidesi', description: 'Kapalı, yumurtalı', price: 300 },
    { category: 'Pideler', name: 'Sucuklu yumurtalı', price: 260 },
    { category: 'Lahmacun', name: 'Lahmacun', description: 'Adet', price: 90 },
    { category: 'Yanında', name: 'Çoban salata', price: 90 },
    { category: 'Tatlılar', name: 'Sütlaç', description: 'Fırında', price: 120 },
    { category: 'İçecekler', name: 'Ayran', price: 40 },
    { category: 'İçecekler', name: 'Çay', price: 25 },
  ],
  corbaci: [
    { category: 'Çorbalar', name: 'İşkembe çorbası', price: 130 },
    { category: 'Çorbalar', name: 'Kelle paça', price: 150 },
    { category: 'Çorbalar', name: 'Mercimek', price: 85 },
    { category: 'Çorbalar', name: 'Yayla', price: 90 },
    { category: 'Çorbalar', name: 'Ezogelin', price: 85 },
    { category: 'Kahvaltılık', name: 'Menemen', price: 190 },
    { category: 'Kahvaltılık', name: 'Sucuklu yumurta', price: 210 },
    { category: 'İçecekler', name: 'Çay', price: 25 },
    { category: 'İçecekler', name: 'Ayran', price: 40 },
  ],
  steakhouse: [
    { category: 'Başlangıçlar', name: 'Et suyu çorbası', price: 150 },
    { category: 'Başlangıçlar', name: 'Carpaccio', price: 380 },
    { category: 'Başlangıçlar', name: 'Kemik iliği', price: 320 },
    { category: 'Etler', name: 'Antrikot', description: '300 gr, kuru dinlendirilmiş', price: 950 },
    { category: 'Etler', name: 'Bonfile', description: '250 gr', price: 1050 },
    { category: 'Etler', name: 'T-Bone', description: '500 gr', price: 1450 },
    { category: 'Etler', name: 'Dana pirzola', price: 890 },
    { category: 'Garnitür', name: 'Fırın patates', price: 130 },
    { category: 'Garnitür', name: 'Izgara sebze', price: 160 },
    { category: 'Tatlılar', name: 'Sufle', price: 220 },
    { category: 'İçecekler', name: 'Ev limonatası', price: 110 },
  ],
  vejetaryen: [
    { category: 'Çorbalar', name: 'Günün çorbası', description: 'Her gün değişir, etsiz', price: 110 },
    { category: 'Ana yemekler', name: 'Buddha bowl', description: 'Kinoa, nohut, avokado, tahin sos', price: 320 },
    { category: 'Ana yemekler', name: 'Mercimek köftesi', price: 240 },
    { category: 'Ana yemekler', name: 'Sebzeli güveç', price: 280 },
    { category: 'Ana yemekler', name: 'Falafel tabağı', price: 290 },
    { category: 'Salatalar', name: 'Mevsim salata', price: 180 },
    { category: 'Salatalar', name: 'Kinoa salatası', price: 230 },
    { category: 'Tatlılar', name: 'Vegan brownie', price: 160 },
    { category: 'İçecekler', name: 'Taze sıkma portakal', price: 130 },
    { category: 'İçecekler', name: 'Bitki çayı', price: 70 },
  ],
  mantici: [
    { category: 'Mantı', name: 'Kayseri mantısı', description: 'Yoğurtlu, naneli tereyağı', price: 280 },
    { category: 'Mantı', name: 'Fırın mantı', price: 300 },
    { category: 'Gözleme', name: 'Peynirli gözleme', price: 160 },
    { category: 'Gözleme', name: 'Kıymalı gözleme', price: 190 },
    { category: 'Gözleme', name: 'Ispanaklı gözleme', price: 170 },
    { category: 'Yanında', name: 'Cacık', price: 70 },
    { category: 'Tatlılar', name: 'Höşmerim', price: 140 },
    { category: 'İçecekler', name: 'Ayran', price: 40 },
    { category: 'İçecekler', name: 'Çay', price: 25 },
  ],
  balik: [
    { category: 'Mezeler', name: 'Deniz börülcesi', price: 140 },
    { category: 'Mezeler', name: 'Kalamar tava', price: 300 },
    { category: 'Mezeler', name: 'Levrek marin', price: 200 },
    { category: 'Ana yemekler', name: 'Levrek ızgara', price: 580 },
    { category: 'Ana yemekler', name: 'Çipura ızgara', price: 550 },
    { category: 'Ana yemekler', name: 'Somon fileto', price: 620 },
    { category: 'Ana yemekler', name: 'Karides güveç', price: 520 },
    { category: 'Tatlılar', name: 'İrmik helvası', price: 150 },
    { category: 'İçecekler', name: 'Şalgam', price: 50 },
  ],
  terasMuzik: [
    { category: 'Başlangıçlar', name: 'Soğuk meze tabağı', description: '5 çeşit', price: 380 },
    { category: 'Başlangıçlar', name: 'Sigara böreği', price: 140 },
    { category: 'Ana yemekler', name: 'Karışık ızgara', description: '2 kişilik', price: 980 },
    { category: 'Ana yemekler', name: 'Tavuk şiş', price: 300 },
    { category: 'Ana yemekler', name: 'Levrek ızgara', price: 560 },
    { category: 'Tatlılar', name: 'Künefe', price: 180 },
    { category: 'İçecekler', name: 'Limonata', price: 110 },
    { category: 'İçecekler', name: 'Türk kahvesi', price: 85 },
  ],
  cigkofte: [
    { category: 'Çiğ köfte', name: 'Çiğ köfte porsiyon', description: '250 gr, etsiz', price: 150 },
    { category: 'Çiğ köfte', name: 'Çiğ köfte dürüm', price: 110 },
    { category: 'Fırından', name: 'Lahmacun', price: 85 },
    { category: 'Fırından', name: 'Peynirli pide', price: 200 },
    { category: 'Yanında', name: 'Mevsim salata', price: 90 },
    { category: 'Tatlılar', name: 'Katmer', description: 'Antep fıstıklı', price: 220 },
    { category: 'İçecekler', name: 'Şalgam', price: 40 },
    { category: 'İçecekler', name: 'Ayran', price: 40 },
  ],
};

/** Katalog restoranını mutfak türüne bağlar. */
export const RESTORAN_MUTFAK: Record<string, keyof typeof MUTFAK_MENULERI> = {
  'meshur-kebapci-halil-altindag': 'kebapci',
  'kose-donerci-kecioren': 'donerci',
  'anadolu-sofrasi-yenimahalle': 'evYemegi',
  'mangalbasi-keyif-etimesgut': 'mangal',
  'pide-evi-karadeniz-mamak': 'pide',
  'corbaci-sabah-sincan': 'corbaci',
  'lezzet-duragi-pursaklar': 'evYemegi',
  'gol-kenari-restoran-golbasi': 'balik',
  'kasap-dukkani-steakhouse-cankaya': 'steakhouse',
  'vejetaryen-mutfak-cankaya': 'vejetaryen',
  'sark-sofrasi-altindag': 'cigkofte',
  'terasta-aksam-yenimahalle': 'terasMuzik',
  'manti-diyari-kecioren': 'mantici',
  'firin-sofra-etimesgut': 'pide',
};
